# Uncomment the next line to define a global platform for your project
platform :ios, '13.1'

target 'MovieDatabase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieDatabase
  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Analytics'
  pod 'Firebase/RemoteConfig'

  target 'MovieDatabaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
